### ISSUE TITLE
Weired Encoding Problems

### ISSUE THREAD

**Issue by Faberle** [rodricios/eatiht#14]
I have an article that is parsed to this:
```
 DFKI ist Gründungsmitglied der EU Big Data Value PPP — DFKI

EU-Kommissarin Neelie Kroes und Jan Sundelin, PrÃ¤sident von Big Data Value Association, unterzeichneten gestern eine Vereinbarung zur Einrichtung einer Ã¶ffentlich.....
````
In the title the ü is properly encoded, in the rest of the content however it fails to encode the special chars properly (eg. ä -> Ã¤). The weired part is that it works fine in the first bit and fails in the rest of the article. Even though the characters are exactly the same in the original article. (http://www.dfki.de/web/presse/pressemitteilungen_intern/2014/dfki-ist-grundungsmitglied-der-eu-big-data-value-ppp)

Cheers 
Christian

**Comment by rodricios** [comment]
I believe this is addressed and fixed by #16
