### ISSUE TITLE
"list index out of range"

### ISSUE THREAD

**Issue by pkpp1233** [rodricios/eatiht#17]
Hey there! This package is amazing.

I'm writing a basic function (which I can add you as a collaborator to, if you'd like) that pulls text from a webpage: https://api.blockspring.com/bs/get-text-from-url

The function ends up getting used by a lot of other projects. So I'm using v2.extract(url) now to pull out the main text from the page, but for some pages I get errors. For instance, today for yahoo.com I get <code>"list index out of range"</code>. Do you know why that might be occurring?

here's the full error:
```
line 234, in extract
    target_tnodes = [tnode for par, tnode in pars_tnodes if hist[0][0] in par]
IndexError: list index out of range
```

UPDATE: I retried it just now and there was no error. Strange!

**Comment by rodricios** [comment]
Strange! I'll have to add fallback-measures for errors like this! 

On a similar note, there's about 3 different implementations that borrow/diverge from the original algorithm, and hopefully I can find time in the near future to squeeze them into a stack of sorts. 

Right now, I'd personally suggest you etv2, the original algo, and then v2, in that order.

**Comment by pkpp1233** [comment]
Ok! Will do. Thank you.
