### ISSUE TITLE
Doesn't seem to work on Mac OS

### ISSUE THREAD

**Issue by Buzut** [rodricios/eatiht#19]
Error when trying to parse:    

    Buzut$ eatiht /Volumes/Storage/analytics/ENI\ Training\ -\ Livre\ Numérique.html 
    Traceback (most recent call last):
      File "/usr/local/bin/eatiht", line 5, in <module>
        pkg_resources.run_script('eatiht==0.1.14', 'eatiht')
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 442, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 1160, in run_script
        execfile(script_filename, namespace, namespace)
      File "/Library/Python/2.6/site-packages/eatiht-0.1.14-py2.6.egg/EGG-INFO/scripts/eatiht", line 3, in <module>
        import eatiht
      File "/Library/Python/2.6/site-packages/eatiht-0.1.14-py2.6.egg/eatiht/__init__.py", line 101, in <module>
        from .eatiht import extract, get_sentence_xpath_tuples, get_xpath_frequencydistribution
      File "/Library/Python/2.6/site-packages/eatiht-0.1.14-py2.6.egg/eatiht/eatiht.py", line 77, in <module>
        from collections import Counter
    ImportError: cannot import name Counter

Install output:

	Buzut$ sudo python setup.py install
	Password:
	running install
	running bdist_egg
	running egg_info
	writing requirements to eatiht.egg-info/requires.txt
	writing eatiht.egg-info/PKG-INFO
	writing top-level names to eatiht.egg-info/top_level.txt
	writing dependency_links to eatiht.egg-info/dependency_links.txt
	reading manifest file 'eatiht.egg-info/SOURCES.txt'
	reading manifest template 'MANIFEST.in'
	writing manifest file 'eatiht.egg-info/SOURCES.txt'
	installing library code to build/bdist.macosx-10.6-universal/egg
	running install_lib
	running build_py
	creating build/bdist.macosx-10.6-universal/egg
	creating build/bdist.macosx-10.6-universal/egg/eatiht
	copying build/lib/eatiht/__init__.py -> build/bdist.macosx-10.6-universal/egg/eatiht
	copying build/lib/eatiht/eatiht.py -> build/bdist.macosx-10.6-universal/egg/eatiht
	copying build/lib/eatiht/eatiht_trees.py -> build/bdist.macosx-10.6-universal/egg/eatiht
	copying build/lib/eatiht/etv2.py -> build/bdist.macosx-10.6-universal/egg/eatiht
	creating build/bdist.macosx-10.6-universal/egg/eatiht/tests
	creating build/bdist.macosx-10.6-universal/egg/eatiht/tests/assets
	copying build/lib/eatiht/tests/assets/__init__.py -> build/bdist.macosx-10.6-universal/egg/eatiht/tests/assets
	copying build/lib/eatiht/tests/assets/foo1.html -> build/bdist.macosx-10.6-universal/egg/eatiht/tests/assets
	copying build/lib/eatiht/tests/assets/full_of_foos.html -> build/bdist.macosx-10.6-universal/egg/eatiht/tests/assets
	copying build/lib/eatiht/tests/assets/google_wiki.html -> build/bdist.macosx-10.6-universal/egg/eatiht/tests/assets
	copying build/lib/eatiht/tests/assets/regex_dot_endings.html -> build/bdist.macosx-10.6-universal/egg/eatiht/tests/assets
	copying build/lib/eatiht/tests/assets/regex_various_endings.html -> build/bdist.macosx-10.6-universal/egg/eatiht/tests/assets
	copying build/lib/eatiht/v2.py -> build/bdist.macosx-10.6-universal/egg/eatiht
	byte-compiling build/bdist.macosx-10.6-universal/egg/eatiht/__init__.py to __init__.pyc
	byte-compiling build/bdist.macosx-10.6-universal/egg/eatiht/eatiht.py to eatiht.pyc
	byte-compiling build/bdist.macosx-10.6-universal/egg/eatiht/eatiht_trees.py to eatiht_trees.pyc
	byte-compiling build/bdist.macosx-10.6-universal/egg/eatiht/etv2.py to etv2.pyc
	byte-compiling build/bdist.macosx-10.6-universal/egg/eatiht/tests/assets/__init__.py to __init__.pyc
	byte-compiling build/bdist.macosx-10.6-universal/egg/eatiht/v2.py to v2.pyc
	creating build/bdist.macosx-10.6-universal/egg/EGG-INFO
	installing scripts to build/bdist.macosx-10.6-universal/egg/EGG-INFO/scripts
	running install_scripts
	running build_scripts
	creating build/bdist.macosx-10.6-universal/egg/EGG-INFO/scripts
	copying build/scripts-2.6/eatiht -> build/bdist.macosx-10.6-universal/egg/EGG-INFO/scripts
	changing mode of build/bdist.macosx-10.6-universal/egg/EGG-INFO/scripts/eatiht to 755
	copying eatiht.egg-info/PKG-INFO -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
	copying eatiht.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
	copying eatiht.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
	copying eatiht.egg-info/not-zip-safe -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
	copying eatiht.egg-info/requires.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
	copying eatiht.egg-info/top_level.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
	creating 'dist/eatiht-0.1.14-py2.6.egg' and adding 'build/bdist.macosx-10.6-universal/egg' to it
	removing 'build/bdist.macosx-10.6-universal/egg' (and everything under it)
	Processing eatiht-0.1.14-py2.6.egg
	removing '/Library/Python/2.6/site-packages/eatiht-0.1.14-py2.6.egg' (and everything under it)
	creating /Library/Python/2.6/site-packages/eatiht-0.1.14-py2.6.egg
	Extracting eatiht-0.1.14-py2.6.egg to /Library/Python/2.6/site-packages
	eatiht 0.1.14 is already the active version in easy-install.pth
	Installing eatiht script to /usr/local/bin

	Installed /Library/Python/2.6/site-packages/eatiht-0.1.14-py2.6.egg
	Processing dependencies for eatiht==0.1.14
	Searching for chardet
	Reading http://pypi.python.org/simple/chardet/
	Best match: chardet 2.3.0
	Downloading https://pypi.python.org/packages/source/c/chardet/chardet-2.3.0.tar.gz#md5=25274d664ccb5130adae08047416e1a8
	Processing chardet-2.3.0.tar.gz
	Running chardet-2.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xcHwiW/chardet-2.3.0/egg-dist-tmp-l3cu59
	warning: no files found matching 'COPYING'
	warning: no files found matching '*.html' under directory 'docs'
	warning: no files found matching '*.css' under directory 'docs'
	warning: no files found matching '*.png' under directory 'docs'
	warning: no files found matching '*.gif' under directory 'docs'
	zip_safe flag not set; analyzing archive contents...
	Adding chardet 2.3.0 to easy-install.pth file
	Installing chardetect script to /usr/local/bin

	Installed /Library/Python/2.6/site-packages/chardet-2.3.0-py2.6.egg
	Searching for lxml
	Reading http://pypi.python.org/simple/lxml/
	Best match: lxml 3.4.2
	Downloading https://pypi.python.org/packages/source/l/lxml/lxml-3.4.2.tar.gz#md5=429e5e771c4be0798923c04cb9739b4e
	Processing lxml-3.4.2.tar.gz
	Running lxml-3.4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QJVQPH/lxml-3.4.2/egg-dist-tmp-k9RYwn
	Building lxml version 3.4.2.
	Building without Cython.
	Using build configuration of libxslt 1.1.24
	/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'bugtrack_url'
	  warnings.warn(msg)
	Adding lxml 3.4.2 to easy-install.pth file

	Installed /Library/Python/2.6/site-packages/lxml-3.4.2-py2.6-macosx-10.6-universal.egg
	Finished processing dependencies for eatiht==0.1.14

**Comment by rodricios** [comment]
Hi @Buzut, it turns out that python 2.6 doesn't have the collections.Counter class :\ It says [here](https://github.com/libextract/libextract/issues/21) that you need python 2.7. Do you think you'd ok with altering eatiht's code to hard code the object? There's also the option of using a newer version of python. 

I understand those are probably pretty involved solutions, sorry about the inconvenience :|

**Comment by rodricios** [comment]
Hi @Buzut, it turns out that python 2.6 doesn't have the collections.Counter class :\ It says [here](https://docs.python.org/2/library/collections.html#collections.Counter) that you need python 2.7. Do you think you'd ok with altering eatiht's code to hard code the object? There's also the option of using a newer version of python. 

I understand those are probably pretty involved solutions, sorry about the inconvenience :|

**Comment by Buzut** [comment]
Hi @rodricios, thanks for your answer. I updated to python 3.4.3 but there's another issue now:

	Buzut:~ Buzut$ python /usr/local/bin/eatiht
	Traceback (most recent call last):
	  File "/usr/local/bin/eatiht", line 4, in <module>
	    import pkg_resources
	ImportError: No module named 'pkg_resources'

**Comment by rodricios** [comment]
Oh man, i'm sorry I missed this comment of yours! I'm honestly not sure how to help you on this one, never had this error come up. Tried asking on stackoverflow by any chance?

**Comment by Buzut** [comment]
It doesn't matter, there was no harm. I didn't try to ask on SO yet, but I will. I'll let you know.
